# Generated by Django 5.1.15 on 2026-08-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, help_text='Nama Lengkap Pengguna', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nis',
            field=models.CharField(blank=True, help_text='Nomor Induk Siswa (untuk role Siswa)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('kurikulum', 'Kurikulum'), ('guru', 'Guru'), ('pengawas', 'Pengawas'), ('siswa', 'Siswa'), ('platform_admin', 'Platform Admin'), ('data_admin', 'Data Admin')], default='siswa', help_text='Peran pengguna dalam sistem CBT', max_length=20),
        ),
    ]
