# Generated by Django 5.1.15 on 2026-08-27 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True, choices=[(10, 'Kelas 10'), (11, 'Kelas 11'), (12, 'Kelas 12')], help_text='Tingkat / Jenjang Kelas (10, 11, 12)', null=True)),
                ('question_text', models.TextField(help_text='Isi Teks Pertanyaan Soal')),
                ('question_image', models.ImageField(blank=True, help_text='Gambar Ilustrasi Soal', null=True, upload_to='questions/')),
                ('option_a', models.TextField(blank=True, default='', help_text='Pilihan Jawaban A')),
                ('image_a', models.ImageField(blank=True, help_text='Gambar Opsi A', null=True, upload_to='questions/options/')),
                ('option_b', models.TextField(blank=True, default='', help_text='Pilihan Jawaban B')),
                ('image_b', models.ImageField(blank=True, help_text='Gambar Opsi B', null=True, upload_to='questions/options/')),
                ('option_c', models.TextField(blank=True, default='', help_text='Pilihan Jawaban C')),
                ('image_c', models.ImageField(blank=True, help_text='Gambar Opsi C', null=True, upload_to='questions/options/')),
                ('option_d', models.TextField(blank=True, default='', help_text='Pilihan Jawaban D')),
                ('image_d', models.ImageField(blank=True, help_text='Gambar Opsi D', null=True, upload_to='questions/options/')),
                ('option_e', models.TextField(blank=True, default='', help_text='Pilihan Jawaban E')),
                ('image_e', models.ImageField(blank=True, help_text='Gambar Opsi E', null=True, upload_to='questions/options/')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', help_text='Kunci Jawaban Benar (A/B/C/D/E)', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Guru Pembuat Soal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to='master_data.teacher')),
                ('subject', models.ForeignKey(blank=True, help_text='Mata Pelajaran Ujian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.subject')),
            ],
            options={
                'verbose_name': 'Butir Soal',
                'verbose_name_plural': 'Bank Soal',
                'db_table': 'questions',
                'ordering': ['created_at'],
            },
        ),
    ]
