# Generated by Django 5.1.15 on 2026-09-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_classroom_major_alter_student_class_room_and_more'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', help_text='Guru Pembuat Soal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to='master_data.teacher'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subject_id', help_text='Mata Pelajaran Ujian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.subject'),
        ),
    ]
