# Generated by Django 5.1.15 on 2026-10-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_classroom_major_alter_student_class_room_and_more'),
        ('questions', '0002_alter_question_created_by_alter_question_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Butir Soal', 'verbose_name_plural': 'Bank Soal'},
        ),
        migrations.AddField(
            model_name='question',
            name='cp_code',
            field=models.CharField(blank=True, choices=[('CP 1', 'CP 1'), ('CP 2', 'CP 2'), ('CP 3', 'CP 3'), ('CP 4', 'CP 4'), ('CP 5', 'CP 5'), ('CP 6', 'CP 6'), ('CP 7', 'CP 7'), ('CP 8', 'CP 8'), ('CP 9', 'CP 9'), ('CP 10', 'CP 10')], db_index=True, default='', help_text='Capaian Pembelajaran (CP 1 - CP 10)', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='cp_name',
            field=models.CharField(blank=True, default='', help_text='Keterangan Topik/Materi Capaian Pembelajaran', max_length=255),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'level', 'cp_code'], name='questions_subject_7e3437_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='questions_created_fc8d7e_idx'),
        ),
    ]
