# Generated by Django 5.1.15 on 2026-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='SMK NEGERI 1 RONGGA', max_length=255)),
                ('school_address', models.TextField(blank=True, default='')),
                ('school_website', models.CharField(blank=True, default='', max_length=255)),
                ('school_email', models.EmailField(blank=True, default='', max_length=255)),
                ('school_phone', models.CharField(blank=True, default='', max_length=50)),
                ('school_postal_code', models.CharField(blank=True, default='', max_length=50)),
                ('academic_year', models.CharField(default='2025/2026', max_length=50)),
                ('semester', models.CharField(default='Ganjil', max_length=50)),
                ('exam_name', models.CharField(default='Penilaian Akhir Semester (PAS)', max_length=255)),
                ('exam_city', models.CharField(default='Rongga', max_length=100)),
                ('exam_date', models.CharField(blank=True, default='', max_length=100)),
                ('headmaster_name', models.CharField(blank=True, default='', max_length=255)),
                ('headmaster_nip', models.CharField(blank=True, default='', max_length=50)),
                ('curriculum_vicedir_name', models.CharField(blank=True, default='', max_length=255)),
                ('curriculum_vicedir_nip', models.CharField(blank=True, default='', max_length=50)),
                ('committee_chairman', models.CharField(blank=True, default='', max_length=255)),
                ('logo_left_url', models.TextField(blank=True, default='', help_text='URL / Base64 logo kiri (cth: Pemda)')),
                ('logo_right_url', models.TextField(blank=True, default='', help_text='URL / Base64 logo kanan (cth: Sekolah)')),
                ('watermark_url', models.TextField(blank=True, default='', help_text='URL / Base64 watermark latar')),
                ('school_seal_url', models.TextField(blank=True, default='', help_text='URL / Base64 cap stempel sekolah')),
                ('headmaster_signature_url', models.TextField(blank=True, default='', help_text='URL / Base64 TTD Kepala Sekolah')),
                ('curriculum_signature_url', models.TextField(blank=True, default='', help_text='URL / Base64 TTD Wakasek Kurikulum')),
                ('header_1', models.CharField(blank=True, default='', help_text='Kop Surat Baris 1', max_length=255)),
                ('header_2', models.CharField(blank=True, default='', help_text='Kop Surat Baris 2', max_length=255)),
                ('header_3', models.CharField(blank=True, default='', help_text='Kop Surat Baris 3', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Setting',
                'verbose_name_plural': 'School Settings',
                'db_table': 'school_settings',
            },
        ),
    ]
