# Generated by Django 5.1.15 on 2026-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='school_majors_list',
            field=models.CharField(blank=True, default='', help_text='Daftar Jurusan', max_length=255),
        ),
    ]
