# Generated by Django 5.1.15 on 2026-08-27 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Kode Jurusan (e.g. RPL, TBSM, TKRO, ATPH)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nama Jurusan (e.g. Rekayasa Perangkat Lunak)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jurusan',
                'verbose_name_plural': 'Daftar Jurusan',
                'db_table': 'majors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Daftar Mata Pelajaran',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama Kelas (e.g. X RPL 1, XI TBSM 2)', max_length=100, unique=True)),
                ('level', models.IntegerField(default=10, help_text='Tingkat Kelas (10, 11, 12)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(blank=True, help_text='Jurusan / Konsentrasi Keahlian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='master_data.major')),
            ],
            options={
                'verbose_name': 'Kelas / Rombel',
                'verbose_name_plural': 'Daftar Kelas / Rombel',
                'db_table': 'classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sso_id', models.UUIDField(blank=True, help_text='SSO Keycloak UUID', null=True, unique=True)),
                ('nis', models.CharField(help_text='Nomor Induk Siswa', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Nama Lengkap Siswa', max_length=255)),
                ('status', models.CharField(default='aktif', help_text='Status Siswa (aktif, mutasi, lulus, dll)', max_length=50)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password_plain', models.CharField(blank=True, default='', help_text='Password default / kartu peserta', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.classroom')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.major')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Daftar Siswa',
                'db_table': 'students',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sso_id', models.UUIDField(blank=True, help_text='SSO Keycloak UUID', null=True, unique=True)),
                ('nip', models.CharField(blank=True, help_text='Nomor Induk Pegawai', max_length=50, null=True)),
                ('full_name', models.CharField(help_text='Nama Lengkap Guru', max_length=255)),
                ('email', models.CharField(blank=True, help_text='Email SSO / Sekolah', max_length=255, null=True, unique=True)),
                ('role_level', models.CharField(choices=[('admin', 'Admin'), ('kurikulum', 'Kurikulum'), ('guru', 'Guru')], default='guru', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guru / GTK',
                'verbose_name_plural': 'Daftar Guru / GTK',
                'db_table': 'teachers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='master_data.classroom')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='master_data.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='master_data.teacher')),
            ],
            options={
                'verbose_name': 'Penugasan Guru',
                'verbose_name_plural': 'Daftar Penugasan Guru',
                'db_table': 'teacher_assignments',
            },
        ),
    ]
