# Generated by Django 5.1.15 on 2026-10-07 05:28

from django.db import migrations


def resolve_levels(apps, schema_editor):
    ClassRoom = apps.get_model('master_data', 'ClassRoom')
    for c in ClassRoom.objects.all():
        if c.name:
            upper = c.name.strip().upper()
            if upper.startswith(('XII ', '12 ', 'XII-', 'XII_')) or upper.startswith('12') or upper.startswith('XII'):
                c.level = 12
            elif upper.startswith(('XI ', '11 ', 'XI-', 'XI_')) or upper.startswith('11') or upper.startswith('XI'):
                c.level = 11
            elif upper.startswith(('X ', '10 ', 'X-', 'X_')) or upper.startswith('10') or upper.startswith('X'):
                c.level = 10
            c.save(update_fields=['level'])


def reverse_resolve_levels(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_classroom_major_alter_student_class_room_and_more'),
    ]

    operations = [
        migrations.RunPython(resolve_levels, reverse_resolve_levels),
    ]
