# Generated by Django 5.1.15 on 2026-08-27 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('questions', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('finished', 'Finished')], default='active', help_text='Status Sesi Ujian (active, locked, finished)', max_length=20)),
                ('violation_count', models.IntegerField(default=0, help_text='Jumlah Pelanggaran / Pindah Layar Terdeteksi')),
                ('score', models.FloatField(default=0.0, help_text='Nilai / Skor Akhir Ujian (0 - 100)')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Waktu Mulai Pengerjaan')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Waktu Selesai Pengerjaan', null=True)),
                ('remaining_seconds', models.IntegerField(default=3600, help_text='Sisa Waktu Pengerjaan dalam Detik')),
                ('schedule', models.ForeignKey(db_column='schedule_id', help_text='Jadwal Ujian Terkait', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='schedules.schedule')),
                ('student', models.ForeignKey(db_column='student_id', help_text='Siswa Peserta Ujian', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='master_data.student')),
            ],
            options={
                'verbose_name': 'Sesi Ujian',
                'verbose_name_plural': 'Daftar Sesi Ujian',
                'db_table': 'exam_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chosen_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text='Pilihan Jawaban Siswa (A, B, C, D, E)', max_length=1, null=True)),
                ('is_doubt', models.BooleanField(default=False, help_text='Status Ragu-ragu Jawaban')),
                ('is_correct', models.BooleanField(blank=True, help_text='Hasil Koreksi Jawaban (True jika Benar)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Waktu Terakhir Jawaban Diperbarui')),
                ('question', models.ForeignKey(db_column='question_id', help_text='Butir Soal Terkait', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='questions.question')),
                ('session', models.ForeignKey(db_column='session_id', help_text='Sesi Ujian Siswa', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exam_engine.examsession')),
            ],
            options={
                'verbose_name': 'Jawaban Siswa',
                'verbose_name_plural': 'Daftar Jawaban Siswa',
                'db_table': 'student_answers',
                'ordering': ['session', 'question'],
            },
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(fields=('student', 'schedule'), name='uq_student_schedule_session'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='uq_session_question_answer'),
        ),
    ]
