server {
    server_name exam.smkn1rongga.sch.id;

    root /opt/exam-jingga/dist;
    index index.html;

    client_max_body_size 50m;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/x-javascript application/xml application/json;

    # Static Assets with Hash (Cached)
    location ~* \.(?:ico|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    # JS and CSS with Hash
    location ~* \.(?:css|js)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # SPA Fallback & No Cache for HTML
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    # Supabase Kong API Proxy
    location ^~ /api/kong/ {
        rewrite ^/api/kong/(.*)$ /$1 break;
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Data Master Central API Proxy (Bypass Browser CORS)
    location ^~ /api/data-master/ {
        rewrite ^/api/data-master/(.*)$ /v1/$1 break;
        proxy_pass https://data.smkn1rongga.sch.id;
        proxy_ssl_server_name on;
        proxy_set_header Host data.smkn1rongga.sch.id;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass_header Authorization;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/exam.smkn1rongga.sch.id/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/exam.smkn1rongga.sch.id/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = exam.smkn1rongga.sch.id) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name exam.smkn1rongga.sch.id;
    return 404;
}
