# Generated by Django 5.1.15 on 2026-08-27 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(default='RUANG 01', help_text='Nama / Nomor Ruangan Ujian (e.g. RUANG 01, Lab Komputer 1)', max_length=100)),
                ('session_name', models.CharField(default='SESI 1', help_text='Nama Sesi Ujian (e.g. SESI 1, SESI 2)', max_length=100)),
                ('exam_period', models.CharField(blank=True, default='', help_text='Periode Ujian (e.g. PAS Ganjil 2025/2026)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(db_column='student_id', help_text='Siswa Peserta Ujian', on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='master_data.student')),
            ],
            options={
                'verbose_name': 'Logistik Siswa',
                'verbose_name_plural': 'Daftar Logistik Siswa',
                'db_table': 'student_logistics',
                'ordering': ['room_name', 'session_name', 'student__full_name'],
            },
        ),
    ]
