# Generated by Django 5.1.15 on 2026-08-27 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Judul / Nama Ujian', max_length=255)),
                ('exam_type', models.CharField(choices=[('UH', 'Ulangan Harian'), ('PTS', 'Penilaian Tengah Semester'), ('PAS', 'Penilaian Akhir Semester'), ('PAT', 'Penilaian Akhir Tahun'), ('SAJ', 'Sumatif Akhir Jenjang')], default='UH', help_text='Jenis Asesmen Ujian', max_length=20)),
                ('duration', models.IntegerField(default=60, help_text='Durasi Ujian dalam Menit')),
                ('target_question_count', models.IntegerField(default=40, help_text='Target Jumlah Butir Soal')),
                ('level', models.IntegerField(blank=True, choices=[(10, 'Kelas 10'), (11, 'Kelas 11'), (12, 'Kelas 12')], help_text='Tingkat / Jenjang Kelas (10, 11, 12)', null=True)),
                ('status', models.CharField(choices=[('pending_selection', 'Tunggu Soal'), ('waiting_validation', 'Tunggu Verifikasi'), ('validated', 'Tervalidasi'), ('ready', 'Siap Ujian'), ('active', 'Sedang Berlangsung'), ('closed', 'Selesai')], default='pending_selection', help_text='Status Siklus Hidup Ujian', max_length=50)),
                ('shuffle_questions', models.BooleanField(default=True, help_text='Acak Urutan Soal untuk Setiap Siswa')),
                ('token', models.CharField(blank=True, help_text='Token Akses Ujian (6 Karakter)', max_length=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='Waktu Mulai Pelaksanaan Ujian', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, db_column='subject_id', help_text='Mata Pelajaran Ujian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='master_data.subject')),
                ('teacher', models.ForeignKey(blank=True, db_column='teacher_id', help_text='Guru Pembuat / Penanggung Jawab Paket Ujian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='master_data.teacher')),
            ],
            options={
                'verbose_name': 'Paket Ujian',
                'verbose_name_plural': 'Daftar Paket Ujian',
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='Waktu Mulai Jadwal Ujian')),
                ('end_time', models.DateTimeField(help_text='Waktu Berakhir Jadwal Ujian')),
                ('token', models.CharField(help_text='Token Akses Ujian', max_length=10)),
                ('session_no', models.IntegerField(default=1, help_text='Nomor Sesi Ujian (0 = Semua Sesi)')),
                ('room_name', models.CharField(blank=True, help_text='Nama Ruang Ujian', max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Terverifikasi'), ('active', 'Aktif'), ('closed', 'Selesai')], default='active', help_text='Status Jadwal Ujian', max_length=50)),
                ('teacher_quota', models.IntegerField(default=0, help_text='Target Kuota Butir Soal Kontribusi Guru ini')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_room', models.ForeignKey(blank=True, db_column='class_id', help_text='Rombongan Belajar / Kelas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='master_data.classroom')),
                ('exam', models.ForeignKey(db_column='exam_id', help_text='Paket Ujian', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.exam')),
                ('teacher', models.ForeignKey(blank=True, db_column='teacher_id', help_text='Guru Pengawas / Pengampu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='master_data.teacher')),
            ],
            options={
                'verbose_name': 'Jadwal Ujian',
                'verbose_name_plural': 'Daftar Jadwal Ujian',
                'db_table': 'schedules',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(default=1, help_text='Nomor Urut Soal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(db_column='exam_id', help_text='Paket Ujian Terkait', on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='schedules.exam')),
                ('question', models.ForeignKey(db_column='question_id', help_text='Butir Soal Terpilih dari Bank Soal', on_delete=django.db.models.deletion.CASCADE, related_name='question_exams', to='questions.question')),
            ],
            options={
                'verbose_name': 'Soal Paket Ujian',
                'verbose_name_plural': 'Daftar Soal Paket Ujian',
                'db_table': 'exam_questions',
                'ordering': ['order_number', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'question'), name='uq_exam_question')],
            },
        ),
    ]
